### ISSUE TITLE
[ENTER] key not intuitive

### ISSUE THREAD

**Issue by jechols** [projecthydra/hydra-editor#82]
The ENTER key effectively clicks the nearest button, rather than submitting the form.  The nearest button may be "add" or "remove" depending if you're on the last item in a list.

For long forms, and/or people who prefer (or require) the keyboard, submitting the form is a bit annoying, and may result in accidental data deletion when hitting ENTER on a field.  The default behavior of an HTML form is that hitting ENTER within most fields will submit the form.

Possibly relevant: http://stackoverflow.com/questions/8294465/making-enter-key-on-an-html-form-submit-instead-of-activating-button

**Comment by jcoyne** [comment]
As far as I know, we haven't changed the default key press behavior in any way. It is using the web browser defaults.

**Comment by jechols** [comment]
I believe that's the case, but it still presents an accessibility issue for keyboard users.  There appears to be an easy fix in the second answer at SO: http://stackoverflow.com/a/16462846/468391 - but I haven't tried it.  I'll submit a PR if I get some time today (and if the fix is in fact as easy as specifying `type="button"`).
