### ISSUE TITLE
Rails 4.1 build is failing

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/hydra-editor#94]
https://travis-ci.org/projecthydra/hydra-editor/jobs/80890598

Due to https://github.com/sass/sass/issues/1656

**Comment by atz** [comment]
All builds failing, currently.

**Comment by jcoyne** [comment]
Needs to be updated to use fcrepo_wrapper/solr_wrapper (or change the generated configs to work with jettywrapper)

**Comment by atz** [comment]
See: https://github.com/projecthydra/hydra-editor/pull/107
